// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBT8GGeS1sJwDMh804jau5un1EJyqQ0KFs',
    appId: '1:647334302519:web:504a663949f1095cfac0b2',
    messagingSenderId: '647334302519',
    projectId: 'chat-2026-2cc2f',
    authDomain: 'chat-2026-2cc2f.firebaseapp.com',
    storageBucket: 'chat-2026-2cc2f.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBn-r9_YlitXJMAJKJGviVVoOXmffcObck',
    appId: '1:647334302519:android:dc8b259d63846871fac0b2',
    messagingSenderId: '647334302519',
    projectId: 'chat-2026-2cc2f',
    storageBucket: 'chat-2026-2cc2f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDq5LdA_h9-7YyhrHqt7O4XTt4OwtxA74o',
    appId: '1:647334302519:ios:21c9ab22ed609a77fac0b2',
    messagingSenderId: '647334302519',
    projectId: 'chat-2026-2cc2f',
    storageBucket: 'chat-2026-2cc2f.firebasestorage.app',
    iosBundleId: 'com.example.chatApp2026',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDq5LdA_h9-7YyhrHqt7O4XTt4OwtxA74o',
    appId: '1:647334302519:ios:21c9ab22ed609a77fac0b2',
    messagingSenderId: '647334302519',
    projectId: 'chat-2026-2cc2f',
    storageBucket: 'chat-2026-2cc2f.firebasestorage.app',
    iosBundleId: 'com.example.chatApp2026',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBT8GGeS1sJwDMh804jau5un1EJyqQ0KFs',
    appId: '1:647334302519:web:30e3e1d60de01272fac0b2',
    messagingSenderId: '647334302519',
    projectId: 'chat-2026-2cc2f',
    authDomain: 'chat-2026-2cc2f.firebaseapp.com',
    storageBucket: 'chat-2026-2cc2f.firebasestorage.app',
  );
}
